included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - build
  - vendor
  - Sources/GimMac/Data/Vendored

strict: true

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - file_length
  - file_header
  - line_length
  - function_body_length
  - closure_body_length
  - cyclomatic_complexity
  - trailing_whitespace
  - pattern_matching_keywords
  - no_extension_access_modifier
  - implicit_return
  - convenience_type
  - function_default_parameter_at_end
  - trailing_closure
  - identifier_name
  - force_unwrapping
  - todo

force_cast: error
force_try: error
